### PR TITLE
Installation script and packaging update for Linux and macOS

### LINKED ISSUE #1005: Docker checksum hardcoded on install.sh didn't match with the one from http://get.docker.com
The install script fails to install docker since there is a wrong checksum hardcoded:

`declare -r docker_checksum='82e964b9a14d294268e4571f542b1508'`

Where it should be: 

```
md5sum /tmp/$docker_script | awk '{print $1}'
1f4ffc2c1884b3e499de90f614ac05a7
```

This triggered the warning:  Cannot install docker. Install it manually: https://docs.docker.com/engine/installation/

### LINKED ISSUE #1006: Linux/Install.sh: Broken paths if installed as root user.
Install.sh can't run properly by root user since /root is outside of /home. Maybe the script should stop with an error message if the user is root, as you can see:

```
root@mw-sw01:/root# echo $GOLEM_DIR
/home//golem/
```

### PR DESCRIPTION
**Pull request by mfranciszkiewicz**
PyInstaller command:
- builds a `tar.gz` distribution for Linux and macOS

Linux installation script:
- fetches the latest release (via github api; **max 60 requests per hour and IP address**)
- updated docker installation script md5 sum (resolves #1005)
- root installation (resolves #1006)

### CODE REVIEW

**Comment by gborowik** [comment]
For macOS works great!

File: Installer/Installer_Linux/install.sh [hunk 1]
```diff
@@ -3,20 +3,37 @@
...
+        print([asset[k] for entry in j             \
+                   if "assets" in entry            \
+               for asset in entry["assets"]        \
+                   if asset[k].find("linux") != -1 \
+              ][0])'
+}
+
 # CONSTANTS
+if [[ $EUID -eq 0 ]]; then
+    declare -r SUDO_USER=$(whoami)
```
Comment (banasiakadam60) [inline Installer/Installer_Linux/install.sh]: When run with `sudo` it will set `SUDO_USER` to `root`
```
adam@adam:~ [15:26:33] $ cat test.sh 
#!/bin/bash

echo $(whoami)
adam@adam:~ [15:26:36] $ ./test.sh 
adam
adam@adam:~ [15:26:38] $ sudo ./test.sh 
root
adam@adam:~ [15:26:44] $ 
```
And we use `SUDO_USER` to get a name of user who called script (which is always launch with root privileges: https://github.com/golemfactory/golem/blob/develop/Installer/Installer_Linux/install.sh#L186)
`SUDO_USER       Set to the login of the user who invoked sudo`
So, if you want to use the user name (which always will be `root`), why don't use just `$USER`? As for me, you should remove this `if`

**Review by banasiakadam60 — CHANGES_REQUESTED** [review]

File: Installer/Installer_Linux/install.sh (hunk 1 above)
Comment (mfranciszkiewicz) [reply Installer/Installer_Linux/install.sh]: I agree, it needs to be fixed. But it doesn't work when user is logged in as root, see https://github.com/golemfactory/golem/issues/1006

**Review by banasiakadam60 — APPROVED** [review]
